### ISSUE TITLE
请问可以支持webhook的签名校验接口吗？

### ISSUE THREAD

**Issue by rockingdice** [smartwalle/paypal#3]
可以参考：

https://github.com/plutov/paypal/blob/master/webhooks.go

[狗头]

**Comment by smartwalle** [comment]
应该是验证了的吧

**Comment by rockingdice** [comment]
> 应该是验证了的吧

我是指的webhook回调回来的验证哦，不是用户付款后的Execute的接口调用~paypal自己的文档上有说，因为webhook任何人都可能给服务器发，所以需要校验确实是来自paypal的而不是其他人的，就需要对header里面的字段进行签名验证，这部分应该是需要收到paypal的回调后开发者这边去校验的，至于怎么校验可能得研究下文档了，我也没有经验…可以看下上面链接里校验的处理方法参考一下…
另外我看有一个api好像和校验有关，不知道是不是调用一下对应的接口就可以了…
总之希望能支持这个功能…

**Comment by smartwalle** [comment]
你看一下  GetWebhookEvent  这个方法里面

**Comment by rockingdice** [comment]
> 你看一下 GetWebhookEvent 这个方法里面

哦好的!!
